version: '3.8'

services:
  free-vps:
    build: .
    image: free-vps-ubuntu:latest
    container_name: free-vps
    restart: unless-stopped
    ports:
      - "6080:6080"
    environment:
      - PORT=6080
      - RESOLUTION=1280x720x24
      - VNC_PASSWORD=
    shm_size: 1gb
